name: Build & Publish docs site
on:
  push:
    branches:
    - main
    paths:
    - 'docs/**'
    - Makefile
    - '.github/**'
  workflow_dispatch:
jobs:
  call-build-and-publish-workflow:
    uses: kinvolk/docs/.github/workflows/build-and-publish-to-gh-pages.yaml@site-gen
    with:
      config: ./docs/config.yaml